title: Andre Norton's Witch World
description: A set of podcasts reviewing all Witch World books
theme: just-the-docs

url: https://godai78.github.io/jtd

aux_links:
  Template Repository: https://github.com/godai78/jtd
